# This workflow builds and tests OCCT on multiple platforms (Windows, macOS, Linux with Clang, and Linux with GCC).
# It is triggered on pull requests to any branch.
# The workflow includes steps to prepare and build the project on each platform, run tests, and upload the results.
# Concurrency is set to ensure that only one instance of the workflow runs per pull request at a time.

name: Build OCCT on Multiple Platforms

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  prepare-and-build-windows-x64:
    name: Prepare and Build on Windows with MSVC (x64)
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Build OCCT
      uses: ./.github/actions/build-occt
      with:
        platform: windows
        compiler: msvc
        artifact-name: install-windows-x64
        use-vtk: 'false'

  prepare-and-build-windows-clang-x64:
    name: Prepare and Build on Windows with Clang (x64)
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Build OCCT
      uses: ./.github/actions/build-occt
      with:
        platform: windows
        compiler: clang
        use-vtk: 'false'
        artifact-name: install-windows-clang-x64

  prepare-and-build-macos-x64:
    name: Prepare and Build on macOS with Clang (x64)
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Build OCCT
      uses: ./.github/actions/build-occt
      with:
        platform: macos
        compiler: clang
        use-vtk: 'false'
        artifact-name: install-macos-x64

  prepare-and-build-macos-gcc-x64:
    name: Prepare and Build on macOS with GCC (x64)
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Build OCCT
      uses: ./.github/actions/build-occt
      with:
        platform: macos
        compiler: gcc
        use-vtk: 'false'
        artifact-name: install-macos-gcc-x64

  prepare-and-build-linux-clang-x64:
    name: Prepare and Build on Ubuntu with Clang (x64)
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Build OCCT
      uses: ./.github/actions/build-occt
      with:
        platform: linux
        compiler: clang
        use-vtk: 'false'
        artifact-name: install-linux-clang-x64

  prepare-and-build-linux-gcc-x64:
    name: Prepare and Build on Ubuntu with GCC (x64)
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Build OCCT
      uses: ./.github/actions/build-occt
      with:
        platform: linux
        compiler: gcc
        use-vtk: 'false'
        artifact-name: install-linux-gcc-x64
